import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { projectsAPI } from '../../services/api';

const statusClass = (status) => `issue-status issue-status--${status}`;
const date = (value) => new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
const errorText = (err) => err.response?.data?.solution?.[0] || err.response?.data?.detail || 'Something went wrong. Please try again.';

function ProjectForm({ onSave, initial = {}, button = 'Create project' }) {
  const [name, setName] = useState(initial.name || ''); const [description, setDescription] = useState(initial.description || ''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(e) { e.preventDefault(); setError(''); setSaving(true); try { await onSave({ name, description }); } catch (err) { setError(errorText(err)); } finally { setSaving(false); } }
  return <form className="project-form" onSubmit={submit}>{error && <div className="alert alert-error">{error}</div>}<div className="form-group"><label>Project name</label><input required maxLength="160" value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Customer portal" /></div><div className="form-group"><label>About this project</label><textarea rows="4" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What does this project do?" /></div><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving…' : button}</button></form>;
}

export default function Projects() {
  const [projects, setProjects] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false);
  const load = async (term = search) => { setLoading(true); try { setProjects((await projectsAPI.getAll(term ? { search: term } : undefined)).data); } finally { setLoading(false); } };
  useEffect(() => { load(''); }, []);
  return <div className="page projects-page"><div className="page-header page-header--row"><div><h1>Projects</h1><p>Your engineering work, issues, and reusable solutions in one place.</p></div><button className="btn btn-primary" onClick={() => setShowForm(!showForm)}>+ New project</button></div>{showForm && <div className="inline-form-card"><h2>Start a project</h2><ProjectForm onSave={async (data) => { await projectsAPI.create(data); setShowForm(false); load(); }} /></div>}<div className="toolbar"><div className="search-box"><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} placeholder="Search projects" /></div><button className="btn btn-secondary" onClick={() => load()}>Search</button></div>{loading ? <div className="page-loading">Loading projects…</div> : projects.length ? <div className="project-grid">{projects.map((project) => <Link to={`/projects/${project.id}`} key={project.id} className="project-card"><div className="project-card-top"><span className={`health health--${project.health}`}>{project.health}</span><span className="project-updated">Updated {date(project.updated_at)}</span></div><h2>{project.name}</h2><p>{project.description || 'No description yet.'}</p><div className="project-metrics"><span><b>{project.issue_count}</b> issues</span><span className="metric-open"><b>{project.open_issue_count}</b> open</span><span className="metric-resolved"><b>{project.resolved_issue_count}</b> solved</span></div></Link>)}</div> : <Empty title="No projects yet" copy="Create a project to begin turning engineering work into searchable knowledge." action={() => setShowForm(true)} label="Create project" />}</div>;
}

function Empty({ title, copy, action, label }) { return <div className="empty-state project-empty"><div className="empty-icon">◆</div><h2>{title}</h2><p>{copy}</p>{action && <button className="btn btn-primary" onClick={action}>{label}</button>}</div>; }

export function ProjectDetail() {
  const { projectId } = useParams(); const [project, setProject] = useState(null); const [issues, setIssues] = useState([]); const [filter, setFilter] = useState(''); const [showIssue, setShowIssue] = useState(false); const [editing, setEditing] = useState(false);
  const load = async () => { const [p, i] = await Promise.all([projectsAPI.getById(projectId), projectsAPI.getIssues(projectId, filter ? { status: filter } : undefined)]); setProject(p.data); setIssues(i.data); };
  useEffect(() => { load(); }, [projectId, filter]);
  if (!project) return <div className="page-loading">Loading project…</div>;
  return <div className="page project-detail"><Link className="back-link" to="/projects">← Projects</Link><div className="project-hero"><div><span className={`health health--${project.health}`}>{project.health}</span><h1>{project.name}</h1>{editing ? <ProjectForm initial={project} button="Save changes" onSave={async (data) => { await projectsAPI.update(projectId, data); setEditing(false); load(); }} /> : <p>{project.description || 'No project description yet.'}</p>}</div><div className="project-hero-actions"><button className="btn btn-secondary" onClick={() => setEditing(!editing)}>Edit project</button><button className="btn btn-primary" onClick={() => setShowIssue(!showIssue)}>+ New issue</button></div></div>{showIssue && <IssueForm onSave={async (data) => { await projectsAPI.createIssue(projectId, data); setShowIssue(false); load(); }} />}<div className="issue-heading"><div><h2>Issues</h2><p>Track active problems and document what resolved them.</p></div><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="not_resolved">Not Resolved</option><option value="resolved">Resolved</option></select></div>{issues.length ? <div className="issue-list">{issues.map((issue) => <Link key={issue.id} to={`/projects/${projectId}/issues/${issue.id}`} className="issue-row"><span className={statusClass(issue.status)}>{issue.status_display}</span><div><h3>{issue.title}</h3><p>{issue.description}</p></div><span className="issue-date">Updated {date(issue.updated_at)}</span></Link>)}</div> : <Empty title="No matching issues" copy="Capture the next problem your team investigates." action={() => setShowIssue(true)} label="New issue" />}</div>;
}

function IssueForm({ onSave, initial = {}, button = 'Create issue' }) { const [data, setData] = useState({ title: initial.title || '', description: initial.description || '', investigation: initial.investigation || '', root_cause: initial.root_cause || '', solution: initial.solution || '', technical_notes: initial.technical_notes || '', status: initial.status || 'open' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const set = (key) => (e) => setData({ ...data, [key]: e.target.value }); async function submit(e) { e.preventDefault(); setSaving(true); setError(''); try { await onSave(data); } catch (err) { setError(errorText(err)); } finally { setSaving(false); } } return <form className="issue-form" onSubmit={submit}><h2>{initial.id ? 'Update issue' : 'Capture an issue'}</h2>{error && <div className="alert alert-error">{error}</div>}<div className="form-group"><label>Issue title</label><input required value={data.title} onChange={set('title')} /></div><div className="form-group"><label>Problem</label><textarea required rows="3" value={data.description} onChange={set('description')} /></div><div className="form-group"><label>Investigation / progress</label><textarea rows="3" value={data.investigation} onChange={set('investigation')} /></div><div className="form-group"><label>Root cause</label><textarea rows="2" value={data.root_cause} onChange={set('root_cause')} /></div><div className="form-group"><label>How was this solved?</label><textarea rows="4" value={data.solution} onChange={set('solution')} placeholder="Required when resolving the issue" /></div><div className="form-group"><label>Technical notes</label><textarea rows="2" value={data.technical_notes} onChange={set('technical_notes')} /></div><div className="form-group"><label>Status</label><select value={data.status} onChange={set('status')}><option value="open">Open</option><option value="not_resolved">Not Resolved</option><option value="resolved">Resolved</option></select></div><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving…' : button}</button></form>; }

export function IssueDetail() { const { projectId, issueId } = useParams(); const [issue, setIssue] = useState(null); const [editing, setEditing] = useState(false); const load = async () => setIssue((await projectsAPI.getIssue(issueId)).data); useEffect(() => { load(); }, [issueId]); if (!issue) return <div className="page-loading">Loading issue…</div>; return <div className="page issue-detail"><Link className="back-link" to={`/projects/${projectId}`}>← {issue.project_name}</Link>{editing ? <IssueForm initial={issue} button="Save issue" onSave={async (data) => { await projectsAPI.updateIssue(issueId, data); setEditing(false); load(); }} /> : <><div className="issue-detail-header"><div><span className={statusClass(issue.status)}>{issue.status_display}</span><h1>{issue.title}</h1><p>Created {date(issue.created_at)} · Updated {date(issue.updated_at)}</p></div><button className="btn btn-primary" onClick={() => setEditing(true)}>Edit issue</button></div><div className="knowledge-flow"><Section title="Problem" value={issue.description} /><Section title="Investigation / progress" value={issue.investigation} empty="No investigation notes yet." /><Section title="Root cause" value={issue.root_cause} empty="Root cause not documented yet." /><Section title="Solution" value={issue.solution} empty="No documented solution yet." strong /><Section title="Technical notes" value={issue.technical_notes} empty="No technical notes." /></div></>}</div>; }
function Section({ title, value, empty, strong }) { return <section className={`knowledge-section ${strong ? 'knowledge-section--solution' : ''}`}><h2>{title}</h2><p>{value || empty}</p></section>; }

export function KnowledgeBase() { const [entries, setEntries] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const load = async () => { setLoading(true); try { setEntries((await projectsAPI.getKnowledgeBase(search ? { search } : undefined)).data); } finally { setLoading(false); } }; useEffect(() => { load(); }, []); return <div className="page"><div className="page-header"><h1>Knowledge Base</h1><p>Resolved engineering issues with reusable solutions.</p></div><div className="toolbar"><div className="search-box"><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} placeholder="Search problems, causes, solutions, or notes" /></div><button className="btn btn-secondary" onClick={load}>Search</button></div>{loading ? <div className="page-loading">Loading knowledge…</div> : entries.length ? <div className="knowledge-grid">{entries.map((entry) => <Link className="knowledge-card" key={entry.id} to={`/projects/${entry.project}/issues/${entry.id}`}><span>{entry.project_name}</span><h2>{entry.title}</h2><p className="knowledge-problem">{entry.description}</p><div className="knowledge-solution"><b>Solution</b><p>{entry.solution}</p></div><small>Updated {date(entry.updated_at)}</small></Link>)}</div> : <Empty title="No resolved issues yet" copy="When an issue is resolved with a documented solution, it will appear here automatically." />}</div>; }
