# Generated by Django 6.1 on 2026-08-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfaq',
            name='pinecone_doc_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
