# Generated by Django 6.0.7 on 2026-07-13 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, default="", max_length=1000)),
                ("budget", models.CharField(blank=True, default="", max_length=100)),
                ("budget_min", models.FloatField(blank=True, null=True)),
                ("budget_max", models.FloatField(blank=True, null=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("job_type", models.CharField(blank=True, default="", max_length=100)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                            ("in_progress", "In Progress"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("total_proposals", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
    ]
